#!/usr/bin/python3
import random
import time

def main():

    random.seed(time.time())
    start = 0
    first_order_length = 10000
    first_order_step = 100
    make = 1
    miss = 0
    make_percent = 0.460123941
    make_miss = []

    for i in range(start, first_order_length):
        shot = random.random()
        if(shot < make_percent):
            #make
            make_miss.append(make)
        else:
            #miss
            make_miss.append(miss)

    data_array = []
    
    for i in range(start,first_order_length,first_order_step):

        extra_term = 0.05
        if(i % 2 == 1):
            extra_term = -extra_term

        makes_per = 0

        for j in range(start,first_order_step):
            if(make_miss[i+j] == 1):
                makes_per += 1

        shot = random.random()

        if(shot < (makes_per/first_order_step + extra_term)):
            data_array.append(make)
        else:
            data_array.append(miss)

    shots = ""

    for shot in data_array:
        shots += str(shot)
    
    print(shots)

main()
